install:
  - pip install -r requirements.txt
addons:
  apt:
    packages:
      - expect
language: python
python:
  - 3.6
script:
  - python -m pytest -v
  - flake8
before_deploy:
  - openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in deploy_key.enc -out deploy_key
#  - eval "$(ssh-agent -s)"
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cat ~/.ssh/config
  - cat /etc/ssh/sshd_config
  - chmod +x ssh-password.sh
deploy:
  provider: script
  skip_cleanup: true
  script: bash ssh-password.sh deploy_key
  on:
    branch: master