install:
- pip install -r requirements.txt
language: python
python:
- 3.6
env:
- SERVER_IP_ADDRESS=35.158.109.210
script:
- python -m pytest -v
- flake
before_install:
- openssl aes-256-cbc -md sha512 -pbkdf2 -iter 1000 -nosalt -in deploy_key.enc -out ./deploy_key
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
  # test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
- ssh -i ./deploy_key root@35.158.109.210 pwd