install:
  - pip install -r requirements.txt
language: python
python:
  - 3.6
env:
  - SERVER_IP_ADDRESS=35.158.109.210
script:
  - python -m pytest -v
  - flake8
before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
